import {
  DESIGN_MD_TOKEN_CATEGORY,
  type DesignMdNormalizedSnapshot,
  type DesignMdNormalizedToken
} from './domain.types';

interface TypographyTokenValue {
  fontFamily?: unknown;
  fontStyle?: unknown;
  fontSize?: unknown;
  lineHeight?: unknown;
  letterSpacing?: unknown;
}

function toCssVariableKey(tokenName: string): string {
  return tokenName.replace(/\./g, '-').replace(/[^a-z0-9-]/gi, '-').toLowerCase();
}

function normalizeDimension(value: string | number): string {
  if (typeof value === 'number') {
    return value === 0 ? '0' : `${value}px`;
  }

  return value;
}

function isTypographyValue(value: string | number | null): value is string {
  return typeof value === 'string' && value.startsWith('{');
}

function parseTypographyValue(value: string): TypographyTokenValue | null {
  try {
    const parsed = JSON.parse(value) as TypographyTokenValue;
    return typeof parsed === 'object' && parsed !== null ? parsed : null;
  } catch {
    return null;
  }
}

function pushTokenLine(lines: string[], key: string, value: string) {
  lines.push(`  --${key}: ${value};`);
}

function getSortedTokensByCategory(
  normalized: DesignMdNormalizedSnapshot,
  category: (typeof DESIGN_MD_TOKEN_CATEGORY)[keyof typeof DESIGN_MD_TOKEN_CATEGORY]
): DesignMdNormalizedToken[] {
  return normalized.tokens
    .filter(token => token.category === category)
    .sort((left, right) => left.name.localeCompare(right.name));
}

export function generateTailwindV4ThemeCss(normalized: DesignMdNormalizedSnapshot): string {
  const lines: string[] = [];
  const colorTokens = getSortedTokensByCategory(normalized, DESIGN_MD_TOKEN_CATEGORY.COLOR);
  const spacingTokens = getSortedTokensByCategory(normalized, DESIGN_MD_TOKEN_CATEGORY.SPACING);
  const componentTokens = getSortedTokensByCategory(
    normalized,
    DESIGN_MD_TOKEN_CATEGORY.COMPONENTS
  );
  const typographyTokens = getSortedTokensByCategory(
    normalized,
    DESIGN_MD_TOKEN_CATEGORY.TYPOGRAPHY
  );

  lines.push('/* Generated by design-md-plugin-v1 */');
  lines.push(`/* page: ${normalized.page.name} (${normalized.page.id}) */`);
  lines.push('@theme {');

  for (const token of colorTokens) {
    if (typeof token.value !== 'string' || token.value.length === 0) {
      continue;
    }

    pushTokenLine(lines, `color-${toCssVariableKey(token.name)}`, token.value);
  }

  for (const token of spacingTokens) {
    if (typeof token.value !== 'number' && typeof token.value !== 'string') {
      continue;
    }

    pushTokenLine(
      lines,
      `spacing-${toCssVariableKey(token.name)}`,
      normalizeDimension(token.value)
    );
  }

  for (const token of componentTokens) {
    if (!token.name.startsWith('radius.') || (typeof token.value !== 'number' && typeof token.value !== 'string')) {
      continue;
    }

    pushTokenLine(
      lines,
      `radius-${toCssVariableKey(token.name)}`,
      normalizeDimension(token.value)
    );
  }

  for (const token of typographyTokens) {
    if (!isTypographyValue(token.value)) {
      continue;
    }

    const parsed = parseTypographyValue(token.value);

    if (parsed == null) {
      continue;
    }

    const tokenKey = toCssVariableKey(token.name);

    if (typeof parsed.fontFamily === 'string' && parsed.fontFamily.length > 0) {
      pushTokenLine(lines, `font-${tokenKey}`, parsed.fontFamily);
    }

    if (typeof parsed.fontSize === 'number' || typeof parsed.fontSize === 'string') {
      pushTokenLine(lines, `text-${tokenKey}`, normalizeDimension(parsed.fontSize));
    }

    if (typeof parsed.lineHeight === 'string' && parsed.lineHeight.length > 0) {
      pushTokenLine(lines, `leading-${tokenKey}`, parsed.lineHeight);
    }

    if (typeof parsed.letterSpacing === 'string' && parsed.letterSpacing.length > 0) {
      pushTokenLine(lines, `tracking-${tokenKey}`, parsed.letterSpacing);
    }

    if (typeof parsed.fontStyle === 'string' && parsed.fontStyle.length > 0) {
      pushTokenLine(lines, `font-style-${tokenKey}`, parsed.fontStyle);
    }
  }

  lines.push('}');
  return `${lines.join('\n').trimEnd()}\n`;
}
